[settings]
legacy_version_file = false
asdf_compat = false

[tools]
python = "latest"
go = "latest"
node = "latest"
rust = { version = "latest", components = "llvm-tools" }
hugo-extended = "latest"
atuin = "latest"
bat = "latest"
bottom = "latest"
eza = "latest"
zellij = "latest"
xh = "latest"
hyperfine = "latest"
fzf = "latest"
fd = "latest"
hexyl = "latest"
ripgrep = "latest"
jj = "latest"
zoxide = "latest"
jq = "latest"
yq = "latest"
lazygit = "latest"
postgres = "15"
difftastic = "latest"
"github:can1357/oh-my-pi" = "latest"
redis = "latest"
